# Generated by Django 4.0.4 on 2022-05-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nom',
            field=models.CharField(default='Categorie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
