# Generated by Django 4.0.4 on 2022-05-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_categorie_nom_categorie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatcommande',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='adresse_ligne1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='adresse_ligne2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='code_postal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='nom_entreprise',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='ville',
            field=models.CharField(max_length=255),
        ),
    ]
