# Generated by Django 4.0.4 on 2022-05-13 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_alter_etatcommande_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereclamation',
            name='envoye_le',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='sujet',
            field=models.CharField(max_length=255),
        ),
    ]
