# Generated by Django 4.0.4 on 2022-05-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_changementetatcommande_etat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtatCommande',
        ),
    ]
