# Generated by Django 4.0.4 on 2022-05-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_delete_etatcommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereclamation',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='changementetatcommande',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='envoye_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='inward',
            field=models.BooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='reclamation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='boutique.reclamation'),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='sujet',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='adresse_ligne2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='est_ouvert',
            field=models.BooleanField(default=True),
        ),
    ]
