# Generated by Django 4.0.4 on 2022-05-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_messagereclamation_lu_alter_categorie_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereclamation',
            name='inward',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boutique.reclamation'),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='sujet',
            field=models.CharField(max_length=255),
        ),
    ]
