# Generated by Django 4.0.4 on 2022-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0008_alter_messagereclamation_inward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagereclamation',
            name='lu',
        ),
        migrations.AddField(
            model_name='reclamation',
            name='nouveaux_messages',
            field=models.BooleanField(default=True),
        ),
    ]
