# Generated by Django 4.0.4 on 2022-05-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutique', '0009_remove_messagereclamation_lu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='changementetatcommande',
            options={'get_latest_by': 'date', 'verbose_name': 'État de la commande', 'verbose_name_plural': 'États de la commande'},
        ),
        migrations.AlterModelOptions(
            name='entreedecommande',
            options={'verbose_name': 'ligne de commande', 'verbose_name_plural': 'lignes de commande'},
        ),
        migrations.AlterModelOptions(
            name='messagereclamation',
            options={'verbose_name': 'message'},
        ),
        migrations.AlterModelOptions(
            name='modele',
            options={'verbose_name': 'modèle de véhicule', 'verbose_name_plural': 'modèles de véhicule'},
        ),
        migrations.AlterModelOptions(
            name='profilclient',
            options={'verbose_name': 'Profil de client', 'verbose_name_plural': 'Profils de clients'},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'verbose_name': 'réclamation'},
        ),
        migrations.AddField(
            model_name='constructeur',
            name='slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.CharField(help_text='Indiquer une version simplifiée du nom de la catégorie, sans espace.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='changementetatcommande',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text="Date à laquelle la commande a obtenu l'état"),
        ),
        migrations.AlterField(
            model_name='changementetatcommande',
            name='etat',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('acc', 'Acceptée'), ('dec', 'Refusée'), ('sen', 'Expédiée'), ('dis', 'Livrée'), ('can', 'Annulée')], max_length=3, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(help_text='Client ayant passé la commande', on_delete=django.db.models.deletion.RESTRICT, to='boutique.profilclient'),
        ),
        migrations.AlterField(
            model_name='entreedecommande',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité souhaitée'),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='envoye_le',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le'),
        ),
        migrations.AlterField(
            model_name='messagereclamation',
            name='inward',
            field=models.BooleanField(help_text="Les messages vers l'intérieur sont ceux qui sont envoyés par le client à un vendeur.", verbose_name="Vers l'intérieur"),
        ),
        migrations.AlterField(
            model_name='modele',
            name='annee',
            field=models.IntegerField(verbose_name='année'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boutique.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='descriptif',
            field=models.TextField(help_text='Donner une description aussi précise que possible'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modeles_compatibles',
            field=models.ManyToManyField(to='boutique.modele', verbose_name='Modèles compatibles'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_ttc',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='prix TTC'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(help_text='Nombre de pièces actuellement en stock'),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='adresse_ligne1',
            field=models.CharField(help_text='Numéro, nom du bâtiment, nom de la rue.', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='adresse_ligne2',
            field=models.CharField(blank=True, help_text='Informations complémentaires', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='nom_entreprise',
            field=models.CharField(help_text="Raison sociale de l'entreprise pour laquelle le client commande", max_length=255),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='profilclient',
            name='user',
            field=models.OneToOneField(help_text='Indiquer ici le compte du client à qui lier les informations', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='commande',
            field=models.ForeignKey(help_text='Commande concernée par la réclamation.', on_delete=django.db.models.deletion.RESTRICT, to='boutique.commande'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='est_ouvert',
            field=models.BooleanField(default=True, help_text="Une réclamation est considérée ouverte tant qu'aucune issue n'a été trouvée.", verbose_name='ouverte'),
        ),
    ]
