# Generated by Django 4.0.4 on 2022-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0010_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(default='', help_text="Numéro ou code permettant d'identifier votre produit", max_length=50, verbose_name='référence'),
            preserve_default=False,
        ),
    ]
